### ISSUE TITLE
Extended Storage failure on WM 0.2.0 and Bep 5.4.8

### ISSUE THREAD

**Issue by ehtacs** [WeylandMod/WeylandMod#11]
Seems to be a compatibility issue. I had to roll back to WM 0.1.5 and Bep to 5.4.7 to get my extended storage to work again. WM 0.2.0 and Bep 5.4.8 seem to not be playing nice.

Additionally, items that are in the new spots are lost when temporarily viewing the chests at a smaller size. Does this indicate that someone not using Extended Storage will destroy items when opening chests?

**Comment by ehtacs** [comment]
Did a clean install on the server with the latest 0.2.0 package exclusively. The client seems to be the issue at the moment.

**Comment by ehtacs** [comment]
I'm a dumbass. Had to enable it on the server (nice!) but that option was not available until after the server ran for the first time. An adjustment to the git could be helpful:

> All features are configurable through the config file io.github.WeylandMod.cfg inside BepInEx config directory. **Config is generated on the server's first run and some options must be set on the server to take effect for the client.**

**Comment by glcoder** [comment]
Yep, you are right, I probably should add config file to package.

> Additionally, items that are in the new spots are lost when temporarily viewing the chests at a smaller size. Does this indicate that someone not using Extended Storage will destroy items when opening chests?

Sounds troubling, I'll double check corner cases.

**Comment by ehtacs** [comment]
The trouble was mine! I had not enabled the Extended Storage on the server level between 0.1.5 and 0.2.0 so items were lost as I migrated poorly 🤣

**Comment by glcoder** [comment]
> The trouble was mine! I had not enabled the Extended Storage on the server level between 0.1.5 and 0.2.0 so items were lost as I migrated poorly 🤣

It's not your fault by any means. I'll be more careful changing configs next time.
