### ISSUE TITLE
Shared Location Done Cross not shared

### ISSUE THREAD

**Issue by KingOfRatCity** [WeylandMod/WeylandMod#20]
Hi,

Great mod works really well so far for everything I have used it for on my dedicated server.  However the one issue I am having is the shared map pins while they work if my friends or I mark a dungeon/crypt for example or copper mine as done with the cross to say it is done that cross is not shared only the pins are.

Am I missing something to allow the cross to be shared?

Thanks and keep up the great work!!!

**Comment by glcoder** [comment]
Hello, right now marking shared pin with cross is not implemented, but we can implement this functionality, I'll note this down.

**Comment by KingOfRatCity** [comment]
> 
> 
> Hello, right now marking shared pin with cross is not implemented, but we can implement this functionality, I'll note this down.

Awesome thank you doesnt have to be an always enabled feature I dont know if some wouldnt like it but just another true/false option in the config would be perfect.  Just means my friends and I would know that the location marked had been completed I'm sure others would also find this useful.

Thank you!!!
