### ISSUE TITLE
Shared Pins Visibility via Server Configuration

### ISSUE THREAD

**Issue by Woovie** [WeylandMod/WeylandMod#21]
# Description
As a server owner, I would like the ability to fully toggle off shared pins server side for my clients.

# Problem
While the setting exists, it does not turn off previously created pins if say it was set to true on initial install. The configuration only created at runtime, so when two of us connected, we got shared pins. I then disabled that feature, but the pins are now stuck displaying on each of our maps with no way to be rid of them.

# Solution
From my point of view, the SharedPins true/false should fully show/hide the pins based on this setting. Previously made pins should be checked for and removed if they remain. Otherwise, players are stuck with pins they cannot remove.

Example of the issue:

![image](https://user-images.githubusercontent.com/7304619/111889837-6f00de80-89a1-11eb-8da9-245fb2d90580.png)

**Comment by glcoder** [comment]
It looks like `SharedPins` configuration option is not working right now, will fix it asap. And I also think it would be a good addition to allow admins (not only owners) to remove shared pins by right clicki on them.

**Comment by Woovie** [comment]
Thanks for confirming. I look forward to the fix.
