### ISSUE TITLE
How exactly does ExtendedServerPassword Work?

### ISSUE THREAD

**Issue by inf1n1tyPa1n** [WeylandMod/WeylandMod#23]
it does not auto generate the permittedlist.txt file.
in what folder do i need to create the permittedlist.txt ?
what do i write in the permittedlist.txt ? ingame name, steam name or steam id?
a bit more information about that would be helpful.
Thanks.

**Comment by KingOfRatCity** [comment]
The file is not part of the mod it is part of the game itself.  It is located in the following location on a client machine or a dedicated server

C:\Users\%USERNAME%\AppData\LocalLow\IronGate\Valheim

**Comment by inf1n1tyPa1n** [comment]
Thanks for the quick Response 
works now perfect!
would be great if you could add this information to your mod post too
so other people that are new also know how to do it :)

**Comment by glcoder** [comment]
@KingOfRatCity thx for helping me out.

@inf1n1tyPa1n I'll add more detailed info on that in future releases.
