### ISSUE TITLE
Shared Pins not working

### ISSUE THREAD

**Issue by shyim** [WeylandMod/WeylandMod#8]
Hey,
I never get the shared pins working. Mod is installed on the server also all clients have it. Sharing explored map does work fine. Is there currently a bug?

**Comment by glcoder** [comment]
Which mod version do you use (version number)?

Is it from releases section on github or is it thunderstore.io package?

Can you provide client and server log?

**Comment by shyim** [comment]
Ahhh. Forgot to copy first BeepIx Was expecting anything is in the zip. Sorry
